FROM eeacms/community

MAINTAINER "David Ichim" <david.ichim@eaudeweb.ro>
WORKDIR /var/local/community.eea.europa.eu
VOLUME  /var/local/community.eea.europa.eu/var/blobstorage
VOLUME  /var/local/community.eea.europa.eu/var/filestorage

CMD bin/zeoserver fg

EXPOSE 8100
